### ISSUE TITLE
Sagemaker Studio extension does not work in version 0.18

### ISSUE THREAD

**Issue by rafaelcb** [aws-samples/sagemaker-run-notebook#8]
I tried installing this using version 0.18 in Sagemaker Studio but I get an error that npm packages are missing.

**Comment by tomfaulhaber** [comment]
I just opened a Studio instance and installed v0.18.0. Are you using a "System terminal" or an "Image terminal" to install? (It should be "System terminal")

Can you attach the command you ran and the output?

**Comment by tomfaulhaber** [comment]
Closing due to lack of info. Please reopen with the requested info if you're still seeing this problem.

**Comment by rafaelcb** [comment]
Hi. I used the System terminal.   The error I get is this:

`bash-4.2$ cat /tmp/jupyterlab-debug-i3ycwro2.log
[LabBuildApp] Building in /opt/conda/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v12.16.1

[LabBuildApp] Building jupyterlab assets (build:prod)
[LabBuildApp] > node /opt/conda/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
[LabBuildApp] yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
error Couldn't find package "@amzn/sagemaker-ui-appstate-plugin@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning @amzn/sagemaker-ui > react-jsonschema-form > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @amzn/sagemaker-ui > react-jsonschema-form > @babel/runtime-corejs2 > core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @amzn/sagemaker-ui > compassql > datalib > topojson@1.6.27: Use topojson-client, topojson-server or topojson-simplify directly.
warning @amzn/sagemaker-ui > compassql > datalib > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @amzn/sagemaker-ui > compassql > datalib > request > har-validator@5.1.5: this library is no longer supported
Error: Couldn't find package "@amzn/sagemaker-ui-components@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-graphql-plugin@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-feature-flags-plugin@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-graphql-client@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-kernel-gql-plugin@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-log-event@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-logger-plugin@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-constants@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-penny-client-plugin@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-sagemaker-plugin@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-profiler-plugin@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-types@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-property-inspector-plugin@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-utils@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-xai@2.11.4" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-data-prep-plugin@^1.0.0" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.11.4.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

[LabBuildApp] npm dependencies failed to install
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 660, in build
    raise RuntimeError(msg)

[LabBuildApp] RuntimeError: npm dependencies failed to install

[LabBuildApp] Exiting application: JupyterLab`

**Comment by rafaelcb** [comment]
I did manage to get it to work in a SageMaker Notebook though

**Comment by jimmycfa** [comment]
I am also seeing this issue with v0.18. I think the latest update to Studio for the new features may have broken something?

**Comment by jimmycfa** [comment]
@tomfaulhaber - Can you reopen this? I am still seeing the same error. I've tried to make a new user and run it in there in Sagemaker Studio to no avail.

**Comment by tomfaulhaber** [comment]
Yup, I see this now too. I'll chase it out.

**Comment by agileurbanite** [comment]
ack will post an update here

**Comment by tomfaulhaber** [comment]
This has now been fixed in SageMaker Studio itself. The fix is still rolling out but it is already in us-west-2, but not yet in us-east-1. When it's rolled out to all the regions (sometime in the next few days, I believe), I'll close the issue.

**Comment by tomfaulhaber** [comment]
Seems to be working in all regions now. Thanks for surfacing this, @rafaelcb and @jimmycfa!

**Comment by songqiang** [comment]
It is 2021-02-05 and my region is us-east-1. I am still seeing the error when trying to install jupyter labextentions. I would appreciate any help.

The command I run from the Terminal is as following:
```
jupyter labextension install @jupyterlab/toc
```

Here is s snippet of the error message
```
Error: Couldn't find package "@amzn/sagemaker-ui-sagemaker-plugin@2.13.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.13.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-types@2.13.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.13.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-log-event@2.13.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.13.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-xai@2.13.1" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.13.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@amzn/sagemaker-ui-data-prep-plugin@^1.0.2" required by "@amzn/sagemaker-ui@file:../extensions/amzn-sagemaker-ui-2.13.1.tgz" on the "npm" registry.
    at /opt/conda/share/jupyter/lab/staging/yarn.js:37186:17
    at Generator.throw (<anonymous>)
    at step (/opt/conda/share/jupyter/lab/staging/yarn.js:310:30)
    at /opt/conda/share/jupyter/lab/staging/yarn.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

npm dependencies failed to install
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

  File "/opt/conda/lib/python3.7/site-packages/jupyterlab/commands.py", line 660, in build
    raise RuntimeError(msg)

RuntimeError: npm dependencies failed to install
```

**Comment by gerold-csendes-epam** [comment]
I face the same issue that @songqiang is having. It seems there is an issue with aws extensions, like `@amzn/sagemaker-ui-
appstate-plugin@2.13.1`.

What could be the problem?
